# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d70c6e9607afb4f6ea0cd68030426b5e524eb8db0d6612f7db648abd17e7d0503fc4c648bf08f966f5bc6368d55d71b562a5a987b2ee792e1aa71ca7119da871

test:
  secret_key_base: bd67c7565dc7ceed0fc379ef5ec53d020c29b76d184919be88e6a530b1f458215b8d0df96a60944f62c94a28427bb382666374e76604f8225870c734a154bffb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
